### ISSUE TITLE
MYSQL , wampserver

### ISSUE THREAD

**Issue by jwdat** [jwdat/Trading-Ideas-by-interests-#5]
I'm trying to put a database on a localhost to start working on connecting python to a database (inserting a msyql in python )

**Comment by z311** [comment]
pycharm, settings, file-settings-project interpreter- +, Mysql.connector-python (specify version 8.0.19)

In a python file:
Import mysql.connector 


Example:
https://www.mysqltutorial.org/mysql-variables

**Comment by z311** [comment]
pycharm, settings; file-settings-project interpreter- +, Mysql.connector-python (specify version 8.0.19)

In a python file:
Import mysql.connector 


Example:

https://www.w3schools.com/python/python_mysql_create_db.asp

**Comment by jwdat** [comment]
> pycharm, settings; file-settings-project interpreter- +, Mysql.connector-python (specify version 8.0.19)
> 
> In a python file:
> Import mysql.connector
> 
> Example:
> 
> https://www.w3schools.com/python/python_mysql_create_db.asp







Thanks man it helped me
